### PR TITLE
Avoid creating tmp_file if --overwrite-in-place option is enabled.

### PR DESCRIPTION
**Pull request by shotat**
## What is this change?

Changed not to create `.isorted` tmp files when `--overwrite-in-place` option is specified.
This change reduces redundant disk IOs and improves performance only when the option is enabled.
Now it uses in-memory buffers instead.

## Why is this needed?

`.isorted` files are created by isort and finally swapped for the original files.
It's not necessary process when overwriting original files directly.

Here are the benchmark results.

```
poetry run pytest tests/benchmark/test_api.py
```

```
### main branch ###

---------------------------------------------------------------------------------- benchmark: 2 tests ----------------------------------------------------------------------------------
Name (time in ms)              Min               Max              Mean            StdDev            Median               IQR            Outliers       OPS            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_sort_file              1.7996 (1.0)      3.2426 (1.0)      2.2094 (1.0)      0.3175 (1.0)      2.1179 (1.00)     0.4647 (1.00)         28;1  452.6046 (1.0)         100          10
test_sort_file_in_place     1.8444 (1.02)     4.7379 (1.46)     2.2292 (1.01)     0.3738 (1.18)     2.1160 (1.0)      0.4631 (1.0)          12;1  448.5892 (0.99)        100          10
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

### this branch ###

---------------------------------------------------------------------------------- benchmark: 2 tests ----------------------------------------------------------------------------------
Name (time in ms)              Min               Max              Mean            StdDev            Median               IQR            Outliers       OPS            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_sort_file_in_place     1.4101 (1.0)      4.2254 (1.0)      1.7057 (1.0)      0.3391 (1.0)      1.6032 (1.0)      0.2694 (1.0)          11;5  586.2820 (1.0)         100          10
test_sort_file              1.8732 (1.33)     4.7795 (1.13)     2.2093 (1.30)     0.3510 (1.04)     2.1044 (1.31)     0.2950 (1.10)         12;4  452.6227 (0.77)        100          10
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

related: https://github.com/PyCQA/isort/pull/1738

### CODE REVIEW

**Review by timothycrosley — APPROVED** [review]
:tada: This is great! Thanks for the well thought out and tested improvement!

**Comment by shotat** [comment]
@timothycrosley Thanks for your review!
Now CI checks are failing under windows environments. It seems due to file permission issues so I'd like to try to fix them.

**Comment by shotat** [comment]
bumped pydantic since safety-db has been updated.
https://github.com/pyupio/safety-db/commit/2def80e3b81f2b1925139ebc4f47d6ce5f21a698#diff-3c561b12084d50ebca9e164979f7df4921085ae29a71bf4e4f4ee1c5f14ae9b5R3591

**Comment by shotat** [comment]
I found that the integration test fails on the main branch because a dependent repository updated 11 hours ago...
https://github.com/plone/plone.app.multilingualindexes/pull/15

**Pull request merged**
