### PR TITLE
Prevent installation of the "tests" package

### PR DESCRIPTION
**Pull request by sbraz**
Hi,
Tests should not be listed under packages, otherwise setup.py attempts to install a "tests" package, causing potential clashes with other packages.

Comparison of the generated setup.py files before and after the change:
```diff
--- a/setup.py   2020-10-10 19:30:58.737358684 +0200
+++ b/setup.py  2020-10-10 19:31:06.787331020 +0200
@@ -6,28 +6,10 @@
  'isort._future',
  'isort._vendored.toml',
  'isort.deprecated',
- 'isort.stdlibs',
- 'tests',
- 'tests.integration',
- 'tests.unit',
- 'tests.unit.example_projects.namespaces.almost-implicit.root',
- 'tests.unit.example_projects.namespaces.almost-implicit.root.nested',
- 'tests.unit.example_projects.namespaces.implicit.root.nested',
- 'tests.unit.example_projects.namespaces.none.root',
- 'tests.unit.example_projects.namespaces.none.root.nested',
- 'tests.unit.example_projects.namespaces.pkg_resource.root',
- 'tests.unit.example_projects.namespaces.pkg_resource.root.nested',
- 'tests.unit.example_projects.namespaces.pkgutil.root',
- 'tests.unit.example_projects.namespaces.pkgutil.root.nested',
- 'tests.unit.profiles']
+ 'isort.stdlibs']
 
 package_data = \
-{'': ['*'],
- 'tests.unit': ['example_projects/namespaces/almost-implicit/*',
-                'example_projects/namespaces/implicit/*',
-                'example_projects/namespaces/none/*',
-                'example_projects/namespaces/pkg_resource/*',
-                'example_projects/namespaces/pkgutil/*']}
+{'': ['*']}
 
 extras_require = \
 {'colors': ['colorama>=0.4.3,<0.5.0'],
```

### CODE REVIEW

**Comment by timothycrosley** [comment]
This looks good to me! I'll have to do some testing later this afternoon to confirm, as poetry used to handle includes poorly - which led to the tests always being included across package types, see: https://github.com/PyCQA/isort/pull/1266 looking at the linked poetry issues quickly it does look like poetry may have fixed this issue now and so this approach will work again. 

Thanks~

~Timothy

**Comment by sbraz** [comment]
The method you used to include tests was probably the only one available at the time.

l spent some time researching before submitting the PR. I found [this issue](https://github.com/python-poetry/poetry/issues/2353) and [this PR](https://github.com/python-poetry/poetry-core/pull/6) that allows for finer-grained inclusion. [The documentation](https://github.com/python-poetry/poetry/pull/2122) was also updated to remove the example advising users to include tests as a package.

**Comment by timothycrosley** [comment]
Thanks so much for doing the research and fixing this long running issue! I was able to confirm locally that it is now working correctly and will merge this into master and do a release shortly that contains just this packaging fix.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
This has been deployed with release 5.6.3.

Thanks!

~Timothy

**Comment by sbraz** [comment]
Works great, thanks a lot :)

**Pull request merged**
