### PR TITLE
Small refactoring in output.py.

### PR DESCRIPTION
**Pull request by sztamas**
Hi @timothycrosley,

How do you feel about accepting refactorings in general?
This would be an example.

I would try to keep them short, provide a description of the why and what and of course try to ensure the changes are safe.

Description:

* Remove duplication in handling `from_first` and make the intent clearer.
* `with_from_import` and `with_straight_import` don't need to know or write to the "global" `section_output`
   - remove `section_output` argument
   - remove `section_output.copy()`
   - functions return their own output without knowing about
     the "global" output
* `sort_ignore_case` already passed in to `_with_from_imports` in `config`. Just use it from there to simplify the argument list and make the 2 helper function arguments more uniform

### CODE REVIEW

**Comment by timothycrosley** [comment]
> In my current situation I do have some time for contributing, which might change in the future, but I guess that's true for everyone, isn't it?

100% true! As much as possible, being a core developer is simply meant to help unblock you enable you to unblock others when you do have time to contribute. Once a member is a core-dev they can leave for months or years and I'll do my best to keep the permissions in tact so you can pick up where you left off. The only major responsibility to take when stepping up to that level is to ensure the security of your account (2 factor authentication enabled, secure password etc) as you will be granted merge access to the repository and if desired permission to deploy to PyPI. I myself have stepped away from the project for an entire year on one occasion, luckily at that time @jdufresne really stepped up and moved the project forward.

**Comment by sztamas** [comment]
Hi @timothycrosley 

My GitHub account is already set up with 2 factor auth and a good password so I'm all good.

I'm ready for the ceremony wherever you are :D 

Is there some core-dev specific documentation beside on the how to contribute docs or we're just going to play it by ear?

Thanks,

Tamas

**Comment by timothycrosley** [comment]
@sztamas, I believe you should be added now!

Sorry for the slight delay, I think I ran into some permission issues immediately after moving isort to the PyCQA organization, but they have since been resolved. Welcome to the project officially!

No good core-dev docs yet, certainly an area of improvement for the project.

Quick ground rules:

- You now are empowered (but not required) to triage issues or review and merge pull requests. If you decide to utilize this, the most important thing is that kindness and courtesy be shown. Second to that would be to deny bad changes, but when possible instead work with the submitter to come to a good solution. 
- Similarly you should now have the ability to triage and close issues. If you choose to utilize this ability: again be kind and aim to find reproduction of the issue. If an issue seems outside of isort's design or inherit limitations feel free to close it, but try to let the requester know why.
- Releases are a second step, if you would like to be able to do those, let me know and we can get you set up with PyPI access.

Finally, have fun! Use these new powers when it will unblock or empower you. Never let it feel like a responsibility. Prioritize the issues or work streams that you find interesting or otherwise bring you joy.

Sidenote: I would say we don't get paid, and that's mostly true. The isort project does take in around $60 a month from tidelift. So far I've used it to organize hackathons, and plan on using it to send swag bags to core-devs, so let me know if you want one. Also, let me know if there is another way of utilizing the funds that you think would be of use.

Thanks again!

~Timothy

**Comment by sztamas** [comment]
Thanks @timothycrosley !

I guess what changes immediately is I create PRs on the main repo instead on my fork like I used to.

In general, everything is a PR and I tend to commit on develop only as an exception with very small fixes.
I prefer PRs for almost everything as they are a good way to group changes together, being able to see what's going on, get code reviews way more easily etc.
What do you think?

I might comment and triage some of the issues and no worries I will be courteous and kind.
One thing I'm happy about is that I can now assign myself to issues I'm working on, that could prevent me working on something someone else is also working on.

I think we can wait with the releases a bit more. That also applies to the swag bag - although who doesn't like some nice swag :-). But joking aside, it is very nice of you to use what isort is making for organizing hackatons, as much as I am concerned you can continue doing that :+1: 

BTW, are there any other core-devs at the moment?

Thanks,

Tamas

**Comment by timothycrosley** [comment]
> BTW, are there any other core-devs at the moment?

There are a few other contributors who I view as core-devs, such as  @jdufresne and @ucodery who both have write access to the repository, but no other active core developers at the moment. My personal goal, is to try to grow to a stable number of 3 active core developers at any given time - where active means making a contribution (of code or triage kind) within roughly a months window. This was one of the the reasons I asked to move the project to PyCQA as well, as the long term health of the project does require a stable contributor base.

> In general, everything is a PR and I tend to commit on develop only as an exception with very small fixes.
I prefer PRs for almost everything as they are a good way to group changes together, being able to see what's going on, get code reviews way more easily etc.
What do you think?

Love that! I think you exemplified that distinction really well, enabling / disabling the airflow tests right in develop, but keeping your feature work in branches. I'll be taking the same approach going forward, and when new core-devs come on board we can encourage them to do the same.

Thanks!

~Timothy

**Pull request merged**
